WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/home/bonfire/urbanu/urban_python/module12/hw4/runner_tests.py", line 24, in test_run
    runner = Runner(42)
             ^^^^^^^^^^
  File "/home/bonfire/urbanu/urban_python/module12/hw4/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(
TypeError: Имя может быть только строкой, передано int
WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/home/bonfire/urbanu/urban_python/module12/hw4/runner_tests.py", line 13, in test_walk
    runner = Runner("test", -5)
             ^^^^^^^^^^^^^^^^^^
  File "/home/bonfire/urbanu/urban_python/module12/hw4/rt_with_exceptions.py", line 13, in __init__
    raise ValueError(f"Скорость не может быть отрицательной, сейчас {speed}")
ValueError: Скорость не может быть отрицательной, сейчас -5
